name: Illoominate Release Build

on:
  pull_request:
    branches: ["main"]
  push:
    tags: ["*-rc*"]
    branches: ["main", "master", "branch-*"]

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '-rc')
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Python package
        run: maturin build --release

      - name: List Linux wheels
        run: find target/wheels/

      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-linux-x86_64
          path: target/wheels/*

  build-macos:
    name: macOS
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, '-rc')
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Python package
        run: maturin build --release

      - name: List Mac wheels
        run: find target/wheels/

      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-macos-x86_64
          path: target/wheels/*

  build-windows:
    name: Windows
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, '-rc')
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Python package
        run: maturin build --release

      - name: List Windows wheels
        run: dir target\wheels\
        shell: powershell

      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-windows-x86_64
          path: target/wheels/*

  merge-build-artifacts:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-macos
      - build-windows
    if: contains(github.event.head_commit.message, '-rc')
    steps:
      - name: Merge Build Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: dist
          pattern: dist-*

